---
- name: download pithos
  become: yes
  become_user: root
  get_url:
    url: '{{pithos_jar_url}}'
    dest: /tmp/{{pithos_jar}}
    mode: '0644'

- name: configurate pithos
  become: yes
  become_user: root
  with_items:
    - f: pithos.yml
      d: /etc
      m: '0644'
    - f: .s3cfg
      d: /root
      m: '0600'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
    
- include: '{{pithos_supervisor | default("systemd")}}.yml'
